import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objs as go
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from datetime import timedelta
from difflib import get_close_matches

# Streamlit settings
st.set_page_config(page_title="AI Market Price Predictor", layout="wide")
st.title("📈 AI Market Price Predictor")

# 🔍 Symbol mapping
name_to_symbol = {

  "Reliance Industries": "RELIANCE.NS",
  "TCS": "TCS.NS",
  "HDFC Bank": "HDFCBANK.NS",
  "ICICI Bank": "ICICIBANK.NS",
  "Infosys": "INFY.NS",
  "Hindustan Unilever": "HINDUNILVR.NS",
  "ITC": "ITC.NS",
  "Bharti Airtel": "BHARTIARTL.NS",
  "State Bank of India": "SBIN.NS",
  "Larsen & Toubro": "LT.NS",
  "Kotak Mahindra Bank": "KOTAKBANK.NS",
  "Axis Bank": "AXISBANK.NS",
  "Sun Pharma": "SUNPHARMA.NS",
  "HCL Technologies": "HCLTECH.NS",
  "Bajaj Finance": "BAJFINANCE.NS",
  "Adani Enterprises": "ADANIENT.NS",
  "Wipro": "WIPRO.NS",
  "Maruti Suzuki": "MARUTI.NS",
  "Mahindra & Mahindra": "M&M.NS",
  "Adani Ports": "ADANIPORTS.NS",
  "UltraTech Cement": "ULTRACEMCO.NS",
  "NTPC": "NTPC.NS",
  "Power Grid": "POWERGRID.NS",
  "Tata Motors": "TATAMOTORS.NS",
  "Tata Steel": "TATASTEEL.NS",
  "Nestle India": "NESTLEIND.NS",
  "Bajaj Finserv": "BAJAJFINSV.NS",
  "JSW Steel": "JSWSTEEL.NS",
  "HDFC Life": "HDFCLIFE.NS",
  "Tech Mahindra": "TECHM.NS",
  "Divi's Labs": "DIVISLAB.NS",
  "Coal India": "COALINDIA.NS",
  "Bajaj Auto": "BAJAJ-AUTO.NS",
  "Grasim Industries": "GRASIM.NS",
  "Britannia Industries": "BRITANNIA.NS",
  "Cipla": "CIPLA.NS",
  "SBI Life": "SBILIFE.NS",
  "Dr Reddy's Labs": "DRREDDY.NS",
  "IndusInd Bank": "INDUSINDBK.NS",
  "Asian Paints": "ASIANPAINT.NS",
  "Havells India": "HAVELLS.NS",
  "Pidilite Industries": "PIDILITIND.NS",
  "Eicher Motors": "EICHERMOT.NS",
  "ICICI Lombard": "ICICIGI.NS",
  "L&T Technology": "LTTS.NS",
  "Hero MotoCorp": "HEROMOTOCO.NS",
  "Dabur India": "DABUR.NS",
  "Berger Paints": "BERGEPAINT.NS",
  "Ambuja Cements": "AMBUJACEM.NS",
  "Siemens": "SIEMENS.NS",
  "Zomato": "ZOMATO.NS",
  "Torrent Pharma": "TORNTPHARM.NS",
  "Tata Power": "TATAPOWER.NS",
  "GAIL": "GAIL.NS",
  "Godrej Consumer": "GODREJCP.NS",
  "Adani Green": "ADANIGREEN.NS",
  "ONGC": "ONGC.NS",
  "Apollo Hospitals": "APOLLOHOSP.NS",
  "Bank of Baroda": "BANKBARODA.NS",
  "SRF": "SRF.NS",
  "Colgate Palmolive": "COLPAL.NS",
  "ICICI Prudential": "ICICIPRULI.NS",
  "DLF": "DLF.NS",
  "JSW Energy": "JSWENERGY.NS",
  "United Spirits": "MCDOWELL-N.NS",
  "Bosch": "BOSCHLTD.NS",
  "Shree Cement": "SHREECEM.NS",
  "AU Small Finance": "AUBANK.NS",
  "Cholamandalam Inv.": "CHOLAFIN.NS",
  "Mphasis": "MPHASIS.NS",
  "Canara Bank": "CANBK.NS",
  "Union Bank": "UNIONBANK.NS",
  "Container Corp": "CONCOR.NS",
  "Indigo (Interglobe Aviation)": "INDIGO.NS",
  "REC Ltd": "RECLTD.NS",
  "Adani Transmission": "ADANITRANS.NS",
  "Adani Total Gas": "ATGL.NS",
  "Varun Beverages": "VBL.NS",
  "Indian Hotels": "INDHOTEL.NS",
  "ICICI Securities": "ICICISEC.NS",
  "Fortis Healthcare": "FORTIS.NS",
  "TVS Motor": "TVSMOTOR.NS",
  "Page Industries": "PAGEIND.NS",
  "Sundaram Finance": "SUNDARMFIN.NS",
  "Jindal Steel & Power": "JINDALSTEL.NS",
  "L&T Finance": "LTF.NS",
  "Muthoot Finance": "MUTHOOTFIN.NS",
  "Balkrishna Ind": "BALKRISIND.NS",
  "Cummins India": "CUMMINSIND.NS",
  "NMDC": "NMDC.NS",
  "Trent": "TRENT.NS",
  "BSE Ltd": "BSE.NS",
  "PVR Inox": "PVRINOX.NS",
  "IDFC First Bank": "IDFCFIRSTB.NS",
  "Ashok Leyland": "ASHOKLEY.NS",
  "IRCTC": "IRCTC.NS",
  "LIC Housing Finance": "LICHSGFIN.NS",
  "Timken India": "TIMKEN.NS",
  "Gland Pharma": "GLAND.NS",
  "LTIMindtree": "LTIM.NS",
  "Sona BLW": "SONACOMS.NS",
  "Navin Fluorine": "NAVINFLUOR.NS",
  "Godrej Properties": "GODREJPROP.NS",
  "KPIT Technologies": "KPITTECH.NS",
  "Whirlpool": "WHIRLPOOL.NS",
  "SKF India": "SKFINDIA.NS",
  "Deepak Nitrite": "DEEPAKNTR.NS",
  "Oberoi Realty": "OBEROIRLTY.NS",
  "Tata Elxsi": "TATAELXSI.NS",
  "Polycab India": "POLYCAB.NS",
  "Aegis Logistics": "AEGISCHEM.NS",
  "L&T Infotech": "LTI.NS",
  "Bharat Forge": "BHARATFORG.NS",
  "IEX": "IEX.NS",
  "Kajaria Ceramics": "KAJARIACER.NS",
  "SBI Cards": "SBICARD.NS",
  "Aarti Industries": "AARTIIND.NS",
  "Granules India": "GRANULES.NS",
  "Indraprastha Gas": "IGL.NS",
  "Blue Star": "BLUESTARCO.NS",
  "Gujarat Gas": "GUJGASLTD.NS",
  "Escorts Kubota": "ESCORTS.NS",
  "Crompton Greaves": "CROMPTON.NS",
  "P&G Hygiene": "PGHH.NS",
  "BASF India": "BASF.NS",
  "ABB India": "ABB.NS",
  "Indian Bank": "INDIANB.NS",
  "Tata Chemicals": "TATACHEM.NS",
  "RBL Bank": "RBLBANK.NS",
  "IDFC": "IDFC.NS",
  "Mahindra Finance": "M&MFIN.NS",
  "Phoenix Mills": "PHOENIXLTD.NS",
  "Ramco Cements": "RAMCOCEM.NS",
  "Balrampur Chini": "BALRAMCHIN.NS",
  "Aditya Birla Cap": "ABCAPITAL.NS",
  "Prestige Estates": "PRESTIGE.NS",
  "Hatsun Agro": "HATSUN.NS",
  "Heidelberg Cement": "HEIDELBERG.NS",
  "Thermax": "THERMAX.NS",
  "APL Apollo Tubes": "APLAPOLLO.NS",
  "Max Healthcare Institute": "MAXHEALTH.NS",
  "UNO Minda": "UNOMINDA.NS",
  "Indian Railway Finance Corporation": "IRFC.NS",
  "Eicher Motors": "EICHERMOT.NS",
  "Sundaram Finance": "SUNDARMFIN.NS",
  "PI Industries": "PIIND.NS",
  "Astral Ltd": "ASTRAL.NS",
  "Havells India": "HAVELLS.NS",
  "AIA Engineering": "AIAENG.NS",
  "ICICI Securities": "ISEC.NS",
  "Tata Chemicals": "TATACHEM.NS",
  "GMR Airports Infra": "GMRINFRA.NS",
  "Berger Paints": "BERGEPAINT.NS",
  "Can Fin Homes": "CANFINHOME.NS",
  "Sonata Software": "SONATSOFTW.NS",
  "Endurance Technologies": "ENDURANCE.NS",
  "Crompton Greaves": "CROMPTON.NS",
  "Dixon Technologies": "DIXON.NS",
  "Balkrishna Industries": "BALKRISIND.NS",
  "Bata India": "BATAINDIA.NS",
  "Indian Hotels Company": "INDHOTEL.NS",
  "Thermax Ltd": "THERMAX.NS",
  "Trent Ltd": "TRENT.NS",
  "V-Guard Industries": "VGUARD.NS",
  "KEI Industries": "KEI.NS",
  "Aditya Birla Capital": "ABCAPITAL.NS",
  "Persistent Systems": "PERSISTENT.NS",
  "Angel One": "ANGELONE.NS",
  "Polycab India": "POLYCAB.NS",
  "Voltas Ltd": "VOLTAS.NS",
  "Indian Energy Exchange": "IEX.NS",
  "Finolex Cables": "FINCABLES.NS",
  "Relaxo Footwears": "RELAXO.NS",
  "RBL Bank": "RBLBANK.NS",
  "Borosil Renewables": "BORORENEW.NS",
  "Aegis Logistics": "AEGISCHEM.NS",
  "Affle India": "AFFLE.NS",
  "Coforge Ltd": "COFORGE.NS",
  "Gland Pharma": "GLAND.NS",
  "Polymedicure Ltd": "POLYMED.NS",
  "Mastek Ltd": "MASTEK.NS",
  "Shree Renuka Sugars": "RENUKA.NS",
  "Manappuram Finance": "MANAPPURAM.NS",
  "BSE Ltd": "BSE.NS",
  "KNR Constructions": "KNRCON.NS",
  "CreditAccess Grameen": "CREDITACC.NS",
  "Jubilant FoodWorks": "JUBLFOOD.NS",
  "Zensar Technologies": "ZENSARTECH.NS",
  "Schaeffler India": "SCHAEFFLER.NS",
  "Minda Corporation": "MINDACORP.NS",
  "Chambal Fertilisers": "CHAMBLFERT.NS",
  "National Aluminium": "NATIONALUM.NS",
  "Karur Vysya Bank": "KARURVYSYA.NS",
  "Hindustan Copper": "HINDCOPPER.NS",
  "Graphite India": "GRAPHITE.NS",
  "TTK Prestige": "TTKPRESTIG.NS",
  "Gujarat Fluorochemicals": "FLUOROCHEM.NS",
  "Sanofi India": "SANOFI.NS",
  "Radico Khaitan": "RADICO.NS",
  "Sula Vineyards": "SULA.NS",
  "Syrma SGS Technology": "SYRMA.NS",
  "Deepak Fertilisers": "DEEPAKFERT.NS",
  "Ujjivan SFB": "UJJIVANSFB.NS",
  "DCM Shriram": "DCMSHRIRAM.NS",
  "Ashok Leyland": "ASHOKLEY.NS",
  "Welspun India": "WELSPUNIND.NS",
  "Zee Entertainment": "ZEEL.NS",
  "IRB Infrastructure": "IRB.NS",
  "NHPC Ltd": "NHPC.NS",
  "Jindal Stainless": "JSL.NS",
  "Spandana Sphoorty": "SPANDANA.NS",
  "CSB Bank": "CSBBANK.NS",
  "Sun TV Network": "SUNTV.NS",
  "Inox Wind": "INOXWIND.NS",
  "Mazagon Dock": "MAZDOCK.NS",
  "Gujarat Gas": "GUJGASLTD.NS",
  "Blue Star": "BLUESTARCO.NS",
  "IRCON International": "IRCON.NS",
  "Inox Green Energy": "INOXGREEN.NS",
  "CMS Info Systems": "CMSINFO.NS",
  "Five-Star Business Finance": "FIVESTAR.NS",
  "Happiest Minds": "HAPPSTMNDS.NS",
  "Tata Elxsi": "TATAELXSI.NS",
  "Kalyan Jewellers": "KALYANKJIL.NS",
  "JBM Auto": "JBMA.NS",
  "Route Mobile": "ROUTE.NS",
  "Godfrey Phillips": "GODFRYPHLP.NS",
  "Edelweiss Financial": "EDELWEISS.NS",
  "PNB Housing Finance": "PNBHOUSING.NS",
  "Varun Beverages": "VBL.NS",
  "Sterlite Technologies": "STLTECH.NS",
  "VA Tech Wabag": "WABAG.NS",
  "Gujarat State Petronet": "GSPL.NS",
  "RailTel Corporation": "RAILTEL.NS",
  "ITI Ltd": "ITI.NS",
  "Ajanta Pharma": "AJANTPHARM.NS",
  "Jyothy Labs": "JYOTHYLAB.NS",
  "Future Retail": "FRETAIL.NS",
  "HFCL Ltd": "HFCL.NS",
  "JK Cement": "JKCEMENT.NS",
  "Sudarshan Chemical": "SUDARSCHEM.NS",
  "Shriram Finance": "SHRIRAMFIN.NS",
  "Century Plyboards": "CENTURYPLY.NS",
  "TeamLease Services": "TEAMLEASE.NS",
  "UCO Bank": "UCOBANK.NS",
  "Ujjivan Financial Services": "UJJIVAN.NS",
  "Kalpataru Projects": "KPIL.NS",
  "Fine Organic": "FINEORG.NS",
  "Indiabulls Housing": "IBULHSGFIN.NS",
  "IDBI Bank": "IDBI.NS",
  "Tamil Nadu Newsprint": "TNPL.NS",
  "Texmaco Rail": "TEXRAIL.NS",
  "Suzlon Energy": "SUZLON.NS",
  "Eveready Industries": "EVEREADY.NS",
  "Orient Electric": "ORIENTELEC.NS",
  "SJVN Ltd": "SJVN.NS",
  "VIP Industries": "VIPIND.NS",
  "Greaves Cotton": "GREAVESCOT.NS",
  "Quess Corp": "QUESS.NS",
  "JTEKT India": "JTEKTINDIA.NS",
  "Equitas Small Finance Bank": "EQUITASBNK.NS",
  "NLC India": "NLCINDIA.NS",
  "Bank of Maharashtra": "MAHABANK.NS",
  "RITES Ltd": "RITES.NS",
  "IDFC Ltd": "IDFC.NS",
  "TV Today Network": "TVTODAY.NS",
  "Balrampur Chini Mills": "BALRAMCHIN.NS",
  "Indraprastha Gas": "IGL.NS",
  "Mirza International": "MIRZAINT.NS",
  "Shilpa Medicare": "SHILPAMED.NS",
  "NBCC India": "NBCC.NS",
  "KNR Constructions": "KNRCON.NS",
  "Gravita India": "GRAVITA.NS",
  "Indian Overseas Bank": "IOB.NS",
  "Astra Microwave Products": "ASTRAMICRO.NS",
  "HLE Glascoat": "HLEGLAS.NS",
  "3M India Ltd": "3MINDIA.NS",
  "ACC Ltd": "ACC.NS",
  "Abbott India Ltd": "ABBOTINDIA.NS",
  "Aditya Birla Fashion & Retail Ltd": "ABFRL.NS",
  "Aavas Financiers Ltd": "AAVAS.NS",
  "ACCELYA Solutions India Ltd": "ACCELYA.NS",
  "Action Construction Equipment Ltd": "ACE.NS",
  "Amara Raja Batteries Ltd": "AMARAJABAT.NS",
  "Amber Enterprises India Ltd": "AMBER.NS",
  "Aegis Logistics Ltd": "AEGISCHEM.NS",
  "Affle (India) Ltd": "AFFLE.NS",
  "Agarwal Industrial Corporation": "AGARIND.NS",
  "AGC Networks Ltd": "AGCNET.NS",
  "AIA Engineering Ltd": "AIAENG.NS",
  "Ajooni Biotech Ltd": "Rare (excluded)",
  "Alembic Pharmaceuticals Ltd": "APLLTD.NS",
  "Alok Industries Ltd": "ALOKINDS.NS",
  "Amrutanjan Health Care Ltd": "AMRUTANJAN.NS",
  "Adlabs Entertainment Ltd": "ADLABS.NS",
  "Ador Welding Ltd": "ADORWELD.NS",
  "Adroit Infotech Ltd": "ADROITINFO.NS",
  "Advanced Enzyme Technologies Ltd": "ADVENZYMES.NS",
  "Advani Hotels & Resorts (India) Ltd": "ADVANIHOTR.NS",
  "AHLUCONT (Ahluwalia Contracts)": "AHLUCONT.NS",
  "Ahimsa Industries Ltd": "AHIMSA.NS",
  "Asian Hotels (West) Ltd": "AHLWEST.NS",
  "Asian Hotels (East) Ltd": "AHLEAST.NS",
  "Action Construction Equipment Ltd": "ACEINTEG.NS",
  "Adani Gas Ltd": "ADANIGAS.NS",
  "Adani Wilmar Ltd": "AWL.NS",
  "ADF Foods Ltd": "ADFFOODS.NS",
  "Adhunik Industries Ltd": "ADHUNIKIND.NS",
  "Adhunik Metaliks Ltd": "ADHUNIK.NS",
  "ANSALAPI (Ansal Properties)": "ANSALAPI.NS",
  "ANSALHSG (Ansal Housing)": "ANSALHSG.NS",
  "Aries Agro Ltd": "ARIES.NS",
  "Arvee Laboratories (India) Ltd": "ARVEE.NS",
  "Arvind Ltd": "ARVIND.NS",
  "Arrow Greentech Ltd": "ARROWGREEN.NS",
  "Arshiya Ltd": "ARSHIYA.NS",
  "ARSS Infra Projects Ltd": "ARSSINFRA.NS",
  "Artimes Medicare Services Ltd": "ARTEMISMED.NS",
  "Aro Granite Industries Ltd": "AROGRANITE.NS",
  "Apollo Micro Systems Ltd": "APOLLO.NS",
  "Apollo Pipes Ltd": "APOLLOPIPE.NS",
  "Apollo Tyres Ltd": "APOLLOTYRE.NS",
  "Gujarat Fluorochemicals Ltd": "FLUOROCHEM.NS",
  "GIPCL (Gujarat Ind Power Co Ltd)": "GIPCL.NS",
  "GESHIP (Great Eastern Shipping Co)": "GESHIP.NS",
  "GFSTEELS (Grand Foundry Ltd)": "GFSTEELS.NS",
  "GFL Ltd": "GFLLIMITED.NS",
  "Gillanders Arbuthnot & Co Ltd": "GILLANDERS.NS",
  "Gillette India Ltd": "GILLETTE.NS",
  "Godfrey Phillips India Ltd": "GODFRYPHLP.NS",
  "GPIL (Genus Power Infra Ltd)": "GENUSPAPER? refine needed",
  "Genesys Intl Corp Ltd": "GENESYS.NS",
  "Geojit Financial Services Ltd": "GEOJITFSL.NS",
  "GIC Housing Finance Ltd": "GICHSGFIN.NS",
  "General Insurance Corp of India": "GICRE.NS",
  "GlaxoSmithKline Pharmaceuticals Ltd": "GLAXO.NS",
  "Glenmark Pharmaceuticals Ltd": "GLENMARK.NS",
  "Global Education Ltd": "GLOBALVECT? cross-check",
  "G L Fine-Chem Ltd": "GLFACELL? skip",
  "Adlabs Entertainment": duplicate,
   "Adani Enterprises": "ADANIENT.NS",
  "Adani Ports & SEZ": "ADANIPORTS.NS",
  "Asian Paints": "ASIANPAINT.NS",
  "Axis Bank": "AXISBANK.NS",
  "Bajaj Auto": "BAJAJ-AUTO.NS",
  "Bajaj Finance": "BAJFINANCE.NS",
  "Bajaj Finserv": "BAJAJFINSV.NS",
  "Bharti Airtel": "BHARTIARTL.NS",
  "BPCL": "BPCL.NS",
  "Britannia Industries": "BRITANNIA.NS",
  "Cipla": "CIPLA.NS",
  "Coal India": "COALINDIA.NS",
  "Divi's Laboratories": "DIVISLAB.NS",
  "Dr. Reddy's Laboratories": "DRREDDY.NS",
  "Eicher Motors": "EICHERMOT.NS",
  "Grasim Industries": "GRASIM.NS",
  "HCL Technologies": "HCLTECH.NS",
  "HDFC Bank": "HDFCBANK.NS",
  "HDFC Life Insurance": "HDFCLIFE.NS",
  "Hero MotoCorp": "HEROMOTOCO.NS",
  "Hindalco Industries": "HINDALCO.NS",
  "Hindustan Unilever": "HINDUNILVR.NS",
  "ICICI Bank": "ICICIBANK.NS",
  "ITC": "ITC.NS",
  "Infosys": "INFY.NS",
  "JSW Steel": "JSWSTEEL.NS",
  "Kotak Mahindra Bank": "KOTAKBANK.NS",
  "Larsen & Toubro": "LT.NS",
  "LTIMindtree": "LTIM.NS",
  "Mahindra & Mahindra": "M&M.NS",
  "Maruti Suzuki": "MARUTI.NS",
  "Nestle India": "NESTLEIND.NS",
  "NTPC": "NTPC.NS",
  "Oil & Natural Gas Corporation": "ONGC.NS",
  "Power Grid Corporation": "POWERGRID.NS",
  "Reliance Industries": "RELIANCE.NS",
  "SBI Life Insurance": "SBILIFE.NS",
  "State Bank of India": "SBIN.NS",
  "Sun Pharmaceuticals": "SUNPHARMA.NS",
  "Tata Consumer Products": "TATACONSUM.NS",
  "Tata Motors": "TATAMOTORS.NS",
  "Tata Steel": "TATASTEEL.NS",
  "TCS": "TCS.NS",
  "Tech Mahindra": "TECHM.NS",
  "Titan Company": "TITAN.NS",
  "UltraTech Cement": "ULTRACEMCO.NS",
  "UPL": "UPL.NS",
  "Wipro": "WIPRO.NS",
  "AU Small Finance Bank": "AUBANK.NS",
  "Axis Bank": "AXISBANK.NS",
  "Bandhan Bank": "BANDHANBNK.NS",
  "Bank of Baroda": "BANKBARODA.NS",
  "Federal Bank": "FEDERALBNK.NS",
  "HDFC Bank": "HDFCBANK.NS",
  "ICICI Bank": "ICICIBANK.NS",
  "IDFC First Bank": "IDFCFIRSTB.NS",
  "IndusInd Bank": "INDUSINDBK.NS",
  "Kotak Mahindra Bank": "KOTAKBANK.NS",
  "Punjab National Bank": "PNB.NS",
  "State Bank of India": "SBIN.NS",
  "HDFC": "HDFC.NS",
  "Bajaj Finserv": "BAJAJFINSV.NS",
  "Power Grid": "POWERGRID.NS",
  "3M India Ltd": "3MINDIA.NS",
  "ACC Ltd": "ACC.NS",
  "Adani Energy Solutions": "ADANIENSOL.NS",
  "Adani Gas Ltd": "ADANIGAS.NS",
  "Adani Wilmar Ltd": "AWL.NS",
  "Aditya Birla Capital Ltd": "ABCAPITAL.NS",
  "Aditya Birla Fashion & Retail Ltd": "ABFRL.NS",
  "AIA Engineering Ltd": "AIAENG.NS",
  "Alembic Pharmaceuticals Ltd": "APLLTD.NS",
  "Amara Raja Batteries Ltd": "AMARAJABAT.NS",
  "Amber Enterprises Ltd": "AMBER.NS",
  "Aurobindo Pharma Ltd": "AUROPHARMA.NS",
  "AU Small Finance Bank": "AUBANK.NS",
  "Bandhan Bank": "BANDHANBNK.NS",
  "Bajaj Holdings & Investments Ltd": "BAJAJHLDNG.NS",
  "Bajaj Housing Finance Ltd": "BAJAJHFL.NS",
  "Bank of Baroda": "BANKBARODA.NS",
  "Bharat Petroleum Corp Ltd": "BPCL.NS",
  "Bharat Forge Ltd": "BHARATFORG.NS",
  "Biocon Ltd": "BIOCON.NS",
  "Cadila Healthcare Ltd": "CADILAHC.NS",
  "Can Fin Homes Ltd": "CANFINHOME.NS",
  "Cochin Shipyard Ltd": "COCHINSHIP.NS",
  "Cipla Ltd": "CIPLA.NS",
  "Coastal Corporation Ltd": "COASTCORP.NS",
  "Container Corp India Ltd": "CONCOR.NS",
  "Coromandel International Ltd": "COROMANDEL.NS",
  "CRISIL Ltd": "CRISIL.NS",
  "DLF Ltd": "DLF.NS",
  "Divi's Laboratories Ltd": "DIVISLAB.NS",
  "Dixon Technologies India Ltd": "DIXON.NS",
  "Edelweiss Financial Services Ltd": "EDELWEISS.NS",
  "Endurance Technologies Ltd": "ENDURANCE.NS",
  "GAIL (India) Ltd": "GAIL.NS",
  "Gland Pharma Ltd": "GLAND.NS",
  "GlaxoSmithKline Pharma Ltd": "GLAXO.NS",
  "GlaxoSmithKline Consumer Healthcare Ltd": "GSKCONS.NS",
  "Glenmark Pharmaceuticals Ltd": "GLENMARK.NS",
  "Godrej Consumer Products Ltd": "GODREJCP.NS",
  "Godrej Industries Ltd": "GODREJIND.NS",
  "Godrej Properties Ltd": "GODREJPROP.NS",
  "Grindwell Norton Ltd": "GRINDWELL.NS",
  "Happiest Minds Technologies Ltd": "HAPPSTMNDS.NS",
  "HDFC Asset Management Co Ltd": "HDFCAMC.NS",
  "Hindustan Zinc Ltd": "HINDZINC.NS",
  "Hindustan Petroleum Corp Ltd": "HINDPETRO.NS",
  "Honeywell Automation India Ltd": "HONAUT.NS",
  "Idfc First Bank Ltd": "IDFCFIRSTB.NS",
  "Indian Energy Exchange Ltd": "IEX.NS",
  "Indraprastha Gas Ltd": "IGL.NS",
  "Indus Towers Ltd": "INDUSTOWER.NS",
  "Inox Wind Ltd": "INOXWIND.NS",
  "Interglobe Aviation Ltd (IndiGo)": "INDIGO.NS",
  "ITC Ltd": "ITC.NS",
  "Jubilant FoodWorks Ltd": "JUBLFOOD.NS",
  "JSW Holdings Ltd": "JSWHLDNG.NS",
  "Karur Vysya Bank Ltd": "KARURVYSYA.NS",
  "KEI Industries Ltd": "KEI.NS",
  "L&T Finance Holdings Ltd": "LTFH.NS",
  "L&T Technology Services Ltd": "LTTS.NS",
  "LIC Housing Finance Ltd": "LICHSGFIN.NS",
  "Linde India Ltd": "LINDEINDIA.NS",
  "Lupin Ltd": "LUPIN.NS",
  "Mazagon Dock Shipbuilders Ltd": "MAZDOCK.NS",
  "MCX (Multi Commodity Exchange India Ltd)": "MCX.NS",
  "Mphasis Ltd": "MPHASIS.NS",
  "NBCC (India) Ltd": "NBCC.NS",
  "NMDC Ltd": "NMDC.NS",
  "NTPC Ltd": "NTPC.NS",
  "Oil India Ltd": "OIL.NS",
  "Page Industries Ltd": "PAGEIND.NS",
  "Petronet LNG Ltd": "PETRONET.NS",
  "Pidilite Industries Ltd": "PIDILITIND.NS",
  "Polycab India Ltd": "POLYCAB.NS",
  "Power Finance Corp Ltd": "PFC.NS",
  "Poonawalla Fincorp Ltd": "POONAWALLA.NS",
  "Railtel Corp Ltd": "RAILTEL.NS",
  "Radico Khaitan Ltd": "RADICO.NS",
  "REC Ltd": "RECLTD.NS",
  "Reliance Power Ltd": "RELIANCEPOWER.NS",
  "Route Mobile Ltd": "ROUTE.NS",
  "Sanofi India Ltd": "SANOFI.NS",
  "Schaeffler India Ltd": "SCHAEFFLER.NS",
  "Shree Cement Ltd": "SHREECEM.NS",
  "Shriram Finance Ltd": "SHRIRAMFIN.NS",
  "SJVN Ltd": "SJVN.NS",
  "Solar Industries India Ltd": "SOLARINDS.NS",
  "Sterlite Technologies Ltd": "STLTECH.NS",
  "Sun TV Network Ltd": "SUNTV.NS",
  "Suzlon Energy Ltd": "SUZLON.NS",
  "Tata Investment Corporation Ltd": "TATAINVEST.NS",
  "Timken India Ltd": "TIMKEN.NS",
  "Torrent Power Ltd": "TORNTPHARM.NS",
  "Torrent Power Ltd": "TORNTPOWER.NS",
  "United Breweries Ltd": "UBL.NS",
  "Vodafone Idea Ltd": "IDEA.NS",
  "Voltas Ltd": "VOLTAS.NS",
  "Welspun Corp Ltd": "WELSPUNIND.NS",
   "Wheelzer": "WZ",
  "Yes Bank Ltd": "YESBANK.NS",
  "Zydus Lifesciences Ltd": "ZYDUSLIFE.NS",
  "APL Apollo Tubes": "APLAPOLLO.NS",
"Max Healthcare Institute": "MAXHEALTH.NS",
"UNO Minda": "UNOMINDA.NS",
"Indian Railway Finance Corporation": "IRFC.NS",
"Aarti Drugs": "AARTIDRUGS.NS",
"Aegis Logistics": "AEGISCHEM.NS",
"Ajanta Pharma": "AJANTPHARM.NS",
"Alkyl Amines": "ALKYLAMINE.NS",
"Amara Raja Energy & Mobility": "AMARAJABAT.NS",
"Angel One": "ANGELONE.NS",
"Apollo Tyres": "APOLLOTYRE.NS",
"Asahi India Glass": "ASAHIINDIA.NS",
"Aster DM Healthcare": "ASTERDM.NS",
"Astral Limited": "ASTRAL.NS",
"Atul Ltd": "ATUL.NS",
"Avanti Feeds": "AVANTIFEED.NS",
"Bajaj Consumer Care": "BAJAJCON.NS",
"Balaji Amines": "BALAMINES.NS",
"Balkrishna Industries": "BALKRISIND.NS",
"Balrampur Chini Mills": "BALRAMCHIN.NS",
"Bank of Maharashtra": "MAHABANK.NS",
"Bata India": "BATAINDIA.NS",
"Berger Paints": "BERGEPAINT.NS",
"Bharat Dynamics": "BDL.NS",
"Bharat Forge": "BHARATFORG.NS",
"Birla Corporation": "BIRLACORPN.NS",
"Blue Star": "BLUESTARCO.NS",
"Bombay Dyeing": "BOMDYEING.NS",
"Can Fin Homes": "CANFINHOME.NS",
"Caplin Point": "CAPLIPOINT.NS",
"Castrol India": "CASTROLIND.NS",
"Central Bank of India": "CENTRALBK.NS",
"Century Plyboards": "CENTURYPLY.NS",
"Chambal Fertilisers": "CHAMBLFERT.NS",
"Chemplast Sanmar": "CHEMPLASTS.NS",
"Clean Science and Technology": "CLEAN.NS",
"CMS Info Systems": "CMSINFO.NS",
"Coal India": "COALINDIA.NS",
"COFORGE": "COFORGE.NS",
"Cyient": "CYIENT.NS",
"Dalmia Bharat": "DALBHARAT.NS",
"Deepak Fertilisers": "DEEPAKFERT.NS",
"Dishman Carbogen Amcis": "DCAL.NS",
"Dr. Lal PathLabs": "LALPATHLAB.NS",
"EID Parry": "EIDPARRY.NS",
"Eicher Motors": "EICHERMOT.NS",
"Equitas Small Finance Bank": "EQUITASBNK.NS",
"Everest Industries": "EVERESTIND.NS",
"Exide Industries": "EXIDEIND.NS",
"Fine Organic": "FINEORG.NS",
"Firstsource Solutions": "FSL.NS",
"Fortis Healthcare": "FORTIS.NS",
"Galaxy Surfactants": "GALAXYSURF.NS",
"Gland Pharma": "GLAND.NS",
"Godfrey Phillips": "GODFRYPHLP.NS",
"Godrej Agrovet": "GODREJAGRO.NS",
"GR Infraprojects": "GRINFRA.NS",
"Greenply Industries": "GREENPLY.NS",
"Greaves Cotton": "GREAVESCOT.NS",
"Grindwell Norton": "GRINDWELL.NS",
"Gujarat Gas": "GUJGASLTD.NS",
"Gujarat Narmada Valley Fertilizers": "GNFC.NS",
"Gujarat State Fertilizers": "GSFC.NS",
"HEG": "HEG.NS",
"HFCL": "HFCL.NS",
"Hikal": "HIKAL.NS",
"Himadri Speciality Chemical": "HSCL.NS",
"Indian Bank": "INDIANB.NS",
"Indian Hotels Company": "INDHOTEL.NS",
"Indigo Paints": "INDIGOPNTS.NS",
"Indraprastha Gas": "IGL.NS",
"Indus Towers": "INDUSTOWER.NS",
"IOL Chemicals and Pharmaceuticals": "IOLCP.NS",
"IPCA Laboratories": "IPCALAB.NS",
"J.K. Cement": "JKCEMENT.NS",
"J.K. Paper": "JKPAPER.NS",
"JB Chemicals": "JBCHEPHARM.NS",
"Jindal Saw": "JINDALSAW.NS",
"Jindal Stainless": "JSL.NS",
"Jubilant FoodWorks": "JUBLFOOD.NS",
"Jyothy Labs": "JYOTHYLAB.NS",
"Kalpataru Projects International": "KALPATPOWR.NS",
"Kansai Nerolac Paints": "KANSAINER.NS",
"KCP": "KCP.NS",
"KNR Constructions": "KNRCON.NS",
"KPI Green Energy": "KPIGREEN.NS",
"KPR Mill": "KPRMILL.NS",
"Laxmi Organic": "LXCHEM.NS",
"Lumax Industries": "LUMAXIND.NS",
"Mahanagar Gas": "MGL.NS",
"Mahindra CIE Automotive": "MAHINDCIE.NS",
"Manappuram Finance": "MANAPPURAM.NS",
"Mastek": "MASTEK.NS",
"Minda Corporation": "MINDACORP.NS",
"Munjal Showa": "MUNJALSHOW.NS",
"Navin Fluorine": "NAVINFLUOR.NS",
"NBCC (India)": "NBCC.NS",
"NCC Ltd": "NCC.NS",
"Nitco": "NITCO.NS",
"NOCIL": "NOCIL.NS",
"NRB Bearings": "NRBBEARING.NS",
"Oberoi Realty": "OBEROIRLTY.NS",
"Oil India": "OIL.NS",
"Orient Electric": "ORIENTELEC.NS",
"PI Industries": "PIIND.NS",
"Persistent Systems": "PERSISTENT.NS",
"Petronet LNG": "PETRONET.NS",
"Pfizer India": "PFIZER.NS",
"Polycab India": "POLYCAB.NS",
"Prestige Estates": "PRESTIGE.NS",
"PVR INOX": "PVRINOX.NS",
"Rallis India": "RALLIS.NS",
"Redington India": "REDINGTON.NS",
"Relaxo Footwears": "RELAXO.NS",
"RHI Magnesita": "RHIM.NS",
"RITES": "RITES.NS",
"Rossell India": "ROSSELLIND.NS",
"Sasken Technologies": "SASKEN.NS",
"Schaeffler India": "SCHAEFFLER.NS",
"Siyaram Silk Mills": "SIYSIL.NS",
"Skipper": "SKIPPER.NS",
"Solar Industries": "SOLARINDS.NS",
"Sonata Software": "SONATSOFTW.NS",
"Sudarshan Chemical": "SUDARSCHEM.NS",
"Sula Vineyards": "SULA.NS",
"Sun TV Network": "SUNTV.NS",
"Suprajit Engineering": "SUPRAJIT.NS",
"Supreme Petrochem": "SPLPETRO.NS",
"Suryoday Small Finance Bank": "SURYODAY.NS",
"Syngene International": "SYNGENE.NS",
"TAAL Enterprises": "TAALENT.NS",
"Tata Investment Corporation": "TATAINVEST.NS",
"TeamLease Services": "TEAMLEASE.NS",
"Tejas Networks": "TEJASNET.NS",
"The Ramco Cements": "RAMCOCEM.NS",
"Thyrocare Technologies": "THYROCARE.NS",
"Time Technoplast": "TIMETECHNO.NS",
"Trent Ltd": "TRENT.NS",
"TV Today Network": "TVTODAY.NS",
"Ujjivan Financial Services": "UJJIVAN.NS",
"Ujjivan Small Finance Bank": "UJJIVANSFB.NS",
"United Breweries": "UBL.NS",
"United Spirits": "MCDOWELL-N.NS",
"Vaibhav Global": "VAIBHAVGBL.NS",
"Varun Beverages": "VBL.NS",
"Venky's": "VENKYS.NS",
"VIP Industries": "VIPIND.NS",
"VST Industries": "VSTIND.NS",
"Welspun India": "WELSPUNIND.NS",
"Westlife Foodworld": "WESTLIFE.NS",
"Zensar Technologies": "ZENSARTECH.NS",
 "Bitcoin": "BTC-USD",
  "Ethereum": "ETH-USD",
  "Tether": "USDT-USD",
  "Ripple": "XRP-USD",
  "Binance Coin": "BNB-USD",
  "Solana": "SOL-USD",
  "USD Coin": "USDC-USD",
  "Dogecoin": "DOGE-USD",
  "TRON": "TRX-USD",
  "Cardano": "ADA-USD",
  "Hyperliquid": "HYPE-USD",
  "Stellar": "XLM-USD",
  "Sui": "SUI-USD",
  "Chainlink": "LINK-USD",
  "Hedera Hashgraph": "HBAR-USD",
  "Bitcoin Cash": "BCH-USD",
  "Avalanche": "AVAX-USD",
  "Wrapped Bitcoin": "WBTC-USD",
  "Polkadot": "DOT-USD",
  "Monero": "XMR-USD",
  "Dai": "DAI-USD",
  "Ethereum Classic": "ETC-USD",
  "LEO Token": "LEO-USD",
  "Aptos": "APT-USD",
  "Lido DAO": "LDO-USD",
  "Arbitrum": "ARB-USD",
  "Internet Computer": "ICP-USD",
  "Quant": "QNT-USD",
  "Fantom": "FTM-USD",
  "Algorand": "ALGO-USD",
  "Flow": "FLOW-USD",
  "Aave": "AAVE-USD",
  "Tezos": "XTZ-USD",
  "The Graph": "GRT-USD",
  "Maker": "MKR-USD",
  "Optimism": "OP-USD",
  "Cronos": "CRO-USD",
  "NEAR Protocol": "NEAR-USD",
  "Filecoin": "FIL-USD",
  "Chiliz": "CHZ-USD",
  "Bitget Token": "BGB-USD",
  "Synthetix": "SNX-USD",
  "Kava": "KAVA-USD",
  "Balancer": "BAL-USD",
  "Compound": "COMP-USD",
  "PancakeSwap": "CAKE-USD",
  "Zcash": "ZEC-USD",
  "Curve DAO Token": "CRV-USD",
  "NEM": "XEM-USD",
  "Dash": "DASH-USD",
  "Helium": "HNT-USD",
  "Zilliqa": "ZIL-USD",
  "Waves": "WAVES-USD",
  "Qtum": "QTUM-USD",
  "OMG Network": "OMG-USD",
  "0x": "ZRX-USD",
  "Nano": "NANO-USD",
  "Ontology": "ONT-USD",
  "Augur": "REP-USD",
  "Siacoin": "SC-USD",
  "Loopring": "LRC-USD",
  "Bitcoin SV": "BSV-USD",
  "HUSD": "HUSD-USD",
  "Terra Classic": "LUNC-USD",
  "SushiSwap": "SUSHI-USD",
  "PAX Gold": "PAXG-USD",
  "UMA": "UMA-USD",
  "Yearn.finance": "YFI-USD",
  "Amp": "AMP-USD",
  "Telcoin": "TEL-USD",
  "Oxen": "OXT-USD",
  "Chia": "XCH-USD",
  "Golem": "GLM-USD",
  "Status": "SNT-USD",
  "Enjin Coin": "ENJ-USD",
  "Basic Attention Token": "BAT-USD",
  "ICON": "ICX-USD",
  "Theta Network": "THETA-USD",
  "Ren": "REN-USD",
  "WazirX": "WRX-USD",
  "Dent": "DENT-USD",
  "Fetch.ai": "FET-USD",
  "Cartesi": "CTSI-USD",
  "Dero": "DERO-USD",
  "Vega Protocol": "VEGA-USD",
  "Numeraire": "NMR-USD",
  "Raydium": "RAY-USD",
  "RSK Infrastructure": "RIF-USD",
  "Celo": "CELO-USD",
  "Maple": "MPL-USD",
  "SuperRare": "RARE-USD",
  "XYO": "XYO-USD",
  "Highstreet": "HIGH-USD",
  "Reef": "REEF-USD",
  "Shiden Network": "SDN-USD",
  "Biconomy": "BICO-USD",
  "Decentral Games": "DG-USD",
  "Radicle": "RAD-USD",
  "Origin Protocol": "OGN-USD",
  "Metal DAO": "MTL-USD",
  "Trust Wallet Token": "TWT-USD",
  "IoTeX": "IOTX-USD",
  "Rally": "RLY-USD",
  "Bella Protocol": "BEL-USD",
  "Verge": "XVG-USD",
  "Aergo": "AERGO-USD",
  "DFI.Money": "YFII-USD",
  "Uquid Coin": "UQC-USD",
  "Arpa Chain": "ARPA-USD",
  "Unibright": "UBT-USD",
  "VITE": "VITE-USD",
  "Rari Governance Token": "RGT-USD",
  "Tellor": "TRB-USD",
   "MX Token": "MX-USD",
  "SafePal": "SFP-USD",
  "LayerZero": "ZRO-USD",
  "zkSync": "ZK-USD",
  "Convex Finance": "CVX-USD",
  "FTX Token": "FTT-USD",
  "Creditcoin": "CTC-USD",
  "Golem": "GLM-USD",
  "Dash": "DASH-USD",
  "Ravencoin": "RVN-USD",
  "MimbleWimbleCoin": "MWC-USD",
  "Decred": "DCR-USD",
  "Flux": "FLUX-USD",
  "Telos": "TLOS-USD",
  "DigiByte": "DGB-USD",
  "Fartcoin": "FARTCOIN-USD",
  "dYdX": "DYDX-USD",
  "Blur": "BLUR-USD",
  "Artificial Superintelligence Alliance": "FET-USD",
  "Rarible": "RARI-USD",
  "Nerve Finance": "NRV-USD",
  "JasmyCoin": "JASMY-USD",
  "Anchor Protocol": "ANC-USD",
  "Liquity": "LQTY-USD",
  "Wonderland": "TIME-USD",
  "Axion": "AXN-USD",
  "Mirror Protocol": "MIR-USD",
  "Olympus": "OHM-USD",
  "Reflect Finance": "RFI? (not precise)",
  "Naptime": "??",
  "Kishu Inu": "KISHU-USD",
  "AIOZ Network": "AIOZ-USD",
  "UFO Gaming": "UFO-USD",
  "Pocket Network": "POKT-USD",
  "Proton": "XPR-USD",
  "AscendEx": "ASD-USD",
  "WAX": "WAXP-USD",
  "FUN": "FUN-USD",
  "VeThor": "VTHO-USD",
  "Share": "SHR-USD",
  "QuarkChain": "QKC-USD",
  "Mask Network": "MASK-USD",
  "Tokemak": "TOKE-USD",
  "Prometeus": "PROM-USD",
  "Moonriver": "MOVR-USD",
  "Steem": "STEEM-USD",
  "Keep Network": "KEEP-USD",
  "Radio Caca": "RACA-USD",
  "Rally": "RLY-USD",
  "inSure DeFi": "SURE-USD",
  "SuperFarm": "SUPER-USD",
  "Pocket Network": "POKT-USD",
  "DOGE Army": "DGAT-USD",
  "Beta Finance": "BETA-USD",
  "BakerySwap": "BAKE-USD",
  "Pirate Chain": "ARRR-USD",
  "ShareToken": "SHR-USD",
  "Alpha Venture DAO": "ALPHA-USD",
  "Raydium": "RAY-USD",
  "Ribbon Finance": "RBN-USD",
  "Songbird": "SGB-USD",
  "Orion Protocol": "ORN-USD",
  "WINkLink": "WIN-USD",
  "Yield Guild Games": "YGG-USD",
  "Pundi X": "PUNDIX-USD",
  "TELLOR": "TRB-USD",
  "Frax Share": "FXS-USD",
  "Aragon": "ANT-USD",
  "Reserve Rights": "RSR-USD",
  "Storj": "STORJ-USD",
  "Gnosis": "GNO-USD",
  "Radicle": "RAD-USD",
  "TomoChain": "TOMO-USD",
  "DFI.Money": "YFII-USD",
  "Keep Network": "KEEP-USD",
  "Celo Dollar": "CUSD-USD",
  "dYdX": "DYDX-USD",
  "Loom Network": "LOOM-USD",
  "WazirX": "WRX-USD",
  "Travala.com": "AVA-USD",
  "Utrust": "UTK-USD",
  "Rally": "RLY-USD",
  "Adventure Gold": "AGLD-USD",
  "Lisk": "LSK-USD",
  "Alpha Venture DAO": "ALPHA-USD",
  "Ampleforth Governance Token": "FORTH-USD",
  "RSK Infrastructure Framework": "RIF-USD",
  "Civic": "CVC-USD",
  "Spell Token": "SPELL-USD",
  "Tellor": "TRB-USD",
  "Celer Network": "CELR-USD",
  "sUSD": "SUSD-USD",
  "XCAD Network": "XCAD-USD",
  "MyNeighborAlice": "ALICE-USD",
  "Sologenic": "SOLO-USD",
  "Alien Worlds": "TLM-USD",
  "Bounce Token": "AUCTION-USD",
  "BitShares": "BTS-USD",
  "Everipedia": "IQ-USD",
  "Efforce": "WOZX-USD",
  "Handshake": "HNS-USD",
  "Wing Finance": "WING-USD",
  "Maple": "MPL-USD",
  "AIOZ Network": "AIOZ-USD",
  "Litentry": "LIT-USD",
  "Opulous": "OPUL-USD",
  "Rarible": "RARI-USD",
  "Marlin": "POND-USD",
  "Kava Lend": "HARD-USD",
  "Phala Network": "PHA-USD",
  "Saito": "SAITO-USD",
  "SelfKey": "KEY-USD",
  "Hifi Finance": "MFT-USD",
  "Bitcoin Gold": "BTG-USD",
  "Bitcoin Diamond": "BCD-USD",
  "Metadium": "META-USD",
  "Tornado Cash": "TORN-USD",
  "Mobox": "MBOX-USD",
  "Refinable": "FINE-USD",
  "AdEx": "ADX-USD",
  "Bluzelle": "BLZ-USD",
  "Meter Governance": "MTRG-USD",
  "LBRY Credits": "LBC-USD",
  "BitMart Token": "BMX-USD",
  "KRYLL": "KRL-USD",
  "Dock": "DOCK-USD",
  "Veritaseum": "VERI-USD",
  "Ethernity Chain": "ERN-USD",
  "VIDT DAO": "VIDT-USD",
  "Polymath": "POLY-USD",
  "REVV": "REVV-USD",
  "Aventus": "AVT-USD",
  "Orion Protocol": "ORN-USD",
  "PowerPool": "CVP-USD",
  "SingularityDAO": "SDAO-USD",
  "GameCredits": "GAME-USD",
  "Decentr": "DEC-USD",
  "BitKan": "KAN-USD",
  "UnFederalReserve": "ERSDL-USD",
  "Achain": "ACT-USD",
  "Peercoin": "PPC-USD",
  "Fei USD": "FEI-USD",
  "Everest": "ID-USD",
  "Ambire AdEx": "ADX-USD",
  "TenX": "PAY-USD",
  "STP Network": "STPT-USD",
  "UniLend Finance": "UFT-USD",
  "Waltonchain": "WTC-USD",
  "Bancor Network": "BNT-USD",
  "VitaDAO": "VITA-USD",
  "YIELD App": "YLD-USD",
  "TokenPocket": "TPT-USD",
  "Melon": "MLN-USD",
  "Propy": "PRO-USD",
  "Uquid Coin": "UQC-USD",
  "AirSwap": "AST-USD",
  "Shyft Network": "SHFT-USD",
  "Tokenlon": "LON-USD",
  "Groestlcoin": "GRS-USD",
  "XMON": "XMON-USD",
  "Request": "REQ-USD",
  "RedFOX Labs": "RFOX-USD",
  "Index Cooperative": "INDEX-USD",
  "Tokamak Network": "TON-USD",
  "Quantum Resistant Ledger": "QRL-USD",
  "Swingby": "SWINGBY-USD",
  "K21": "K21-USD",
  "Impossible Finance": "IF-USD",
  "Pluton": "PLU-USD",
  "OpenOcean": "OOE-USD",
  "SuperFarm": "SUPER-USD",
  "Perpetual Protocol": "PERP-USD",
  "APENFT": "NFT-USD",
  "Bounce": "AUCTION-USD",
  "Bella Protocol": "BEL-USD",
  "Solanium": "SLIM-USD",
  "Snowbank": "SB-USD",
  "Vesper": "VSP-USD",
  "Mossland": "MOC-USD",
  "Wanchain": "WAN-USD",
  "Zenon": "ZNN-USD",
  "InsurAce": "INSUR-USD",
  "Deeper Network": "DPR-USD",
  "Impossible Decentralized Incubator Access": "IDIA-USD",
  "Onomy Protocol": "NOM-USD",
  "SALT": "SALT-USD",
  "BounceBit": "BB-USD",
  "XSGD": "XSGD-USD",
  "Centrifuge": "CFG-USD",
  "Nash Exchange": "NEX-USD",
  "HOPR": "HOPR-USD",
  "xToken": "XTK-USD",
  "Zeon": "ZEON-USD",
  "CarVertical": "CV-USD",
  "Phoenix Global": "PHB-USD",
  "Xend Finance": "XEND-USD",
  "Tokenomy": "TEN-USD",
  "Rubic": "RBC-USD",
  "BoringDAO": "BOR-USD",
  "Cortex": "CTXC-USD",
  "Qredo": "QRDO-USD",
  "SwftCoin": "SWFTC-USD",
  "Sora": "XOR-USD",
  "Particl": "PART-USD",
  "Phala Network": "PHA-USD",
  "MASK Network": "MASK-USD",
  "XCAD Network": "XCAD-USD",
  "MyNeighborAlice": "ALICE-USD",
  "Alien Worlds": "TLM-USD",
  "Bounce Token": "AUCTION-USD",
  "BitShares": "BTS-USD",
  "Everipedia": "IQ-USD",
  "Efforce": "WOZX-USD",
  "Handshake": "HNS-USD",
  "Wing Finance": "WING-USD",
  "Maple": "MPL-USD",
  "AIOZ Network": "AIOZ-USD",
  "Litentry": "LIT-USD",
  "Opulous": "OPUL-USD",
  "Rarible": "RARI-USD",
  "Marlin": "POND-USD",
  "Kava Lend": "HARD-USD",
  "Saito": "SAITO-USD",
  "SelfKey": "KEY-USD",
  "Hifi Finance": "MFT-USD",
  "Bitcoin Gold": "BTG-USD",
  "Bitcoin Diamond": "BCD-USD",
  "Metadium": "META-USD",
  "Tornado Cash": "TORN-USD",
  "Mobox": "MBOX-USD",
  "Refinable": "FINE-USD",
  "AdEx": "ADX-USD",
  "Bluzelle": "BLZ-USD",
  "Meter Governance": "MTRG-USD",
  "LBRY Credits": "LBC-USD",
  "BitMart Token": "BMX-USD",
  "Kryll": "KRL-USD",
  "Dock": "DOCK-USD",
  "Veritaseum": "VERI-USD",
  "Ethernity Chain": "ERN-USD",
  "VIDT DAO": "VIDT-USD",
  "Polymath": "POLY-USD",
  "REVV": "REVV-USD",
  "Aventus": "AVT-USD",
  "Orion Protocol": "ORN-USD",
  "PowerPool": "CVP-USD",
  "SingularityDAO": "SDAO-USD",
  "GameCredits": "GAME-USD",
  "Decentr": "DEC-USD",
  "BitKan": "KAN-USD",
  "UnFederalReserve": "ERSDL-USD",
  "Achain": "ACT-USD",
  "Peercoin": "PPC-USD",
  "Fei USD": "FEI-USD",
  "Everest": "ID-USD",
  "Ambire AdEx": "ADX-USD",
  "TenX": "PAY-USD",
  "STP Network": "STPT-USD",
  "UniLend Finance": "UFT-USD",
  "Waltonchain": "WTC-USD",
  "Bancor Network": "BNT-USD",
  "VitaDAO": "VITA-USD",
  "YIELD App": "YLD-USD",
  "TokenPocket": "TPT-USD",
  "Melon": "MLN-USD",
  "Propy": "PRO-USD",
  "Uquid Coin": "UQC-USD",
  "AirSwap": "AST-USD",
  "Shyft Network": "SHFT-USD",
  "Tokenlon": "LON-USD",
  "Groestlcoin": "GRS-USD",
  "XMON": "XMON-USD",
  "RefreshToken": "RFUEL-USD",
  "RedFOX Labs": "RFOX-USD",
  "Index Cooperative": "INDEX-USD",
  "Tokamak Network": "TON-USD",
  "Quantum Resistant Ledger": "QRL-USD",
  "Swingby": "SWINGBY-USD",
  "Impossible Finance": "IF-USD",
  "Pluton": "PLU-USD",
  "OpenOcean": "OOE-USD",
  "SuperFarm": "SUPER-USD",
  "Perpetual Protocol": "PERP-USD",
  "APENFT": "NFT-USD",
  "Bounce": "AUCTION-USD",
  "Bella Protocol": "BEL-USD",
  "Solanium": "SLIM-USD",
  "Snowbank": "SB-USD",
  "Vesper": "VSP-USD",
  "Mossland": "MOC-USD",
  "Wanchain": "WAN-USD",
  "Zenon": "ZNN-USD",
  "InsurAce": "INSUR-USD",
  "Deeper Network": "DPR-USD",
  "IDIA (Impossible DAO)": "IDIA-USD",
  "Onomy Protocol": "NOM-USD",
  "SALT": "SALT-USD",
  "BounceBit": "BB-USD",
  "XSGD": "XSGD-USD",
  "Centrifuge": "CFG-USD",
  "Nash Exchange": "NEX-USD",
  "HOPR": "HOPR-USD",
  "xToken": "XTK-USD",
  "Zeon": "ZEON-USD",
  "CarVertical": "CV-USD",
  "Phoenix Global": "PHB-USD",
  "Xend Finance": "XEND-USD",
  "Tokenomy": "TEN-USD",
  "Rubic": "RBC-USD",
  "BoringDAO": "BOR-USD",
  "Cortex": "CTXC-USD",
  "Qredo": "QRDO-USD",
  "SwftCoin": "SWFTC-USD",
  "Sora": "XOR-USD",
  "Particl": "PART-USD",
  "Pepe": "PEPE-USD",
  "Floki Inu": "FLOKI-USD"
  
}

# 🔍 Search bar
query = st.text_input("🔍 Enter Stock/Crypto/Forex name or symbol", value="bitcoin").strip().lower()

symbol = name_to_symbol.get(query)
if not symbol:
    matches = get_close_matches(query, name_to_symbol.keys(), n=1, cutoff=0.6)
    if matches:
        symbol = name_to_symbol[matches[0]]
        st.success(f"✅ Found: {matches[0].title()} → {symbol}")
    else:
        symbol = query.upper()
        st.warning(f"⚠ Using as symbol: {symbol}")

# 🧠 Model selector
model_choice = st.selectbox("🧠 Select Forecast Model", ["Linear Regression", "XGBoost"])

# 📉 Download data
try:
    data = yf.download(symbol, period="7d", interval="15m", progress=False)
    if data.empty:
        st.error("❌ Symbol not found or no data available.")
    else:
        df = data[['Close']].dropna().copy()

        def forecast_price(df, model_type="Linear", steps=1):
            scaler = MinMaxScaler()
            scaled = scaler.fit_transform(df)
            X, y = [], []
            for i in range(60, len(scaled) - steps):
                X.append(scaled[i-60:i].flatten())
                y.append(scaled[i+steps-1][0])
            if not X:
                return np.nan
            X, y = np.array(X), np.array(y)

            if model_type == "Linear":
                model = LinearRegression()
            else:
                model = XGBRegressor(n_estimators=100, learning_rate=0.1, verbosity=0)

            model.fit(X, y)
            x_input = scaled[-60:].reshape(1, -1)
            prediction = model.predict(x_input)
            return scaler.inverse_transform([[prediction[0]]])[0][0]

        # 🔮 Make predictions
        next_15 = forecast_price(df, model_type=model_choice.split()[0], steps=1)
        next_day = forecast_price(df, model_type=model_choice.split()[0], steps=96)

        # 💰 Show metrics
        def format_price(value):
            if value >= 1:
                return f"${value:,.2f}"
            elif value >= 0.01:
                return f"${value:,.4f}"
            else:
                return f"${value:,.11f}"
         
        st.metric("💰 Current Price", format_price(float(df['Close'].iloc[-1])))
        st.metric("⏱ Forecast (15 mins)", format_price(next_15) if not np.isnan(next_15) else "N/A")
        st.metric("📅 Forecast (Tomorrow)", format_price(next_day) if not np.isnan(next_day) else "N/A")

        st.markdown("---")
        st.markdown("### 📊 Interactive Charts")

        df['Time'] = df.index
        df['Forecast_15m'] = np.nan
        df.loc[df.index[-1], 'Forecast_15m'] = next_15

   # 📈 Line Chart
       fig = go.Figure()
       fig.add_trace(go.Scatter(x=df['Time'], y=df['Close'], name='Price', mode='lines+markers'))
       fig.add_trace(go.Scatter(
           x=[df['Time'].iloc[-1] + timedelta(minutes=15)],
           y=[next_15],
           mode='markers+text',
           name='15-min Forecast',
           text=["Forecast"],
           textposition="top center"
       ))
       fig.update_layout(title=f"{symbol} Price Forecast", xaxis_title="Time", yaxis_title="Price")

    # 🕯 Candlestick Chart
       fig2 = go.Figure(data=[go.Candlestick(
           x=data.index,
           open=data['Open'],
           high=data['High'],
           low=data['Low'],
           close=data['Close']
       )])
       fig2.update_layout(title="Candlestick Chart", xaxis_title="Time", yaxis_title="Price")

     # 📊 Bar Chart
       fig3 = go.Figure(data=[go.Bar(x=df['Time'], y=df['Close'], name='Bar')])
       fig3.update_layout(title="Bar Chart", xaxis_title="Time", yaxis_title="Price")

       st.plotly_chart(fig, use_container_width=True)
       st.plotly_chart(fig2, use_container_width=True)
       st.plotly_chart(fig3, use_container_width=True)

except Exception as e:
    st.error(f"❌ Error: {e}")
